"""
Profile generation.

IoX renders whatever the node definition declares, so the profile is built
from the configuration at start up: only the metrics the user asked for get a
driver, and the temperature editor follows the configured unit.  The files are
only rewritten -- and updateProfile() only called -- when the resulting profile
actually changes, so a restart with an unchanged configuration is a no-op.
"""

import os

from .registry import (EDITORS, E_BOOL, E_TEMP, METRICS, mount_drivers)

NODE_ID = 'SYSSTATS'
NLS_PREFIX = 'SS'
NODE_NAME = 'System Stats'
NODE_ICON = 'Output'

HEADER = '<!-- generated by eisy-polyg-stats, do not edit -->\n'


def driver_layout(config):
    """(driver, label, editor) for the node, in display order."""
    layout = [('ST', 'Status', E_BOOL)]
    for metric in METRICS:
        if not config.is_on(metric.name):
            continue
        if metric.dynamic:
            layout.extend(mount_drivers(config.mounts))
        else:
            layout.extend(metric.drivers)
    return layout


def editor_specs(config):
    """Editor id -> range attributes, with the temperature unit applied."""
    specs = {}
    for _, _, editor in driver_layout(config):
        spec = dict(EDITORS[editor])
        if editor == E_TEMP and config.temp_unit == 'F':
            spec.update({'uom': 17, 'min': -60, 'max': 480})
        specs[editor] = spec
    return specs


def precisions(config):
    """Driver -> decimal places, used to scale values for IoX."""
    specs = editor_specs(config)
    return {driver: specs[editor]['prec']
            for driver, _, editor in driver_layout(config)}


def _nodedef(config):
    lines = [HEADER, '<nodeDefs>\n',
             '  <nodeDef id="%s" nls="%s">\n' % (NODE_ID, NLS_PREFIX),
             '    <sts>\n']
    for driver, _, editor in driver_layout(config):
        lines.append('      <st id="%s" editor="%s" />\n' % (driver, editor))
    lines += ['    </sts>\n',
              '    <cmds>\n',
              '      <sends />\n',
              '      <accepts>\n',
              '        <cmd id="QUERY" />\n',
              '      </accepts>\n',
              '    </cmds>\n',
              '  </nodeDef>\n',
              '</nodeDefs>\n']
    return ''.join(lines)


def _editors(config):
    lines = [HEADER, '<editors>\n']
    for editor, spec in sorted(editor_specs(config).items()):
        lines.append('  <editor id="%s">\n' % editor)
        lines.append('    <range uom="%(uom)s" min="%(min)s" max="%(max)s" '
                     'prec="%(prec)s" />\n' % spec)
        lines.append('  </editor>\n')
    lines.append('</editors>\n')
    return ''.join(lines)


def _nls(config):
    lines = ['# generated by eisy-polyg-stats, do not edit\n\n',
             'ND-%s-NAME = %s\n' % (NODE_ID, NODE_NAME),
             'ND-%s-ICON = %s\n' % (NODE_ID, NODE_ICON),
             'CMD-%s-QUERY-NAME = Query\n\n' % NLS_PREFIX]
    unit = ' (°%s)' % config.temp_unit
    for driver, label, editor in driver_layout(config):
        if editor == E_TEMP:
            label += unit
        lines.append('ST-%s-%s-NAME = %s\n' % (NLS_PREFIX, driver, label))
    return ''.join(lines)


def write(config, path='profile'):
    """Write the profile.  Returns True when anything changed on disk."""
    files = {
        os.path.join(path, 'nodedef', 'nodedefs.xml'): _nodedef(config),
        os.path.join(path, 'editor', 'editors.xml'): _editors(config),
        os.path.join(path, 'nls', 'en_us.txt'): _nls(config),
    }
    changed = False
    for name, content in files.items():
        os.makedirs(os.path.dirname(name), exist_ok=True)
        if _read(name) != content:
            with open(name, 'w') as handle:
                handle.write(content)
            changed = True

    # IoX caches the profile by version, so it has to be bumped whenever the
    # generated files change or the new drivers are never picked up.
    version_file = os.path.join(path, 'version.txt')
    if changed:
        try:
            version = int(_read(version_file) or 0)
        except ValueError:
            version = 0
        with open(version_file, 'w') as handle:
            handle.write('%d\n' % (version + 1))
    return changed


def _read(name):
    try:
        with open(name) as handle:
            return handle.read().strip() if name.endswith('version.txt') \
                else handle.read()
    except OSError:
        return None
