#!/usr/bin/env python3
"""
Regenerate the metric table in README.md from the registry.

Run after adding, removing or renaming a metric or driver:

    python3 tools/update_docs.py

`tests/test_plugin.py` fails if the README is out of date, so the table can
never drift from the code.
"""

import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, ROOT)

from sysstats.registry import markdown_table  # noqa: E402

START = '<!-- METRIC TABLE START -- generated by tools/update_docs.py -->'
END = '<!-- METRIC TABLE END -->'
README = os.path.join(ROOT, 'README.md')


def render():
    return '%s\n%s\n%s' % (START, markdown_table(), END)


def current(text):
    """The table block as it stands in the README, or None."""
    if START not in text or END not in text:
        return None
    head, _, rest = text.partition(START)
    body, _, _ = rest.partition(END)
    return START + body + END


def main():
    with open(README) as handle:
        text = handle.read()
    block = current(text)
    if block is None:
        print('No table markers in README.md, add them first:\n%s\n%s'
              % (START, END))
        return 1
    if block == render():
        print('README.md metric table is up to date')
        return 0
    with open(README, 'w') as handle:
        handle.write(text.replace(block, render()))
    print('README.md metric table regenerated')
    return 0


if __name__ == '__main__':
    sys.exit(main())
